# Configuration for testing

^test:
  bind:
    default:
      listen: 0.0.0.0:3005

      # To have a complete URLs in the tests
      mount:  http://localhost:3005

  database:
    redis: redis://localhost:6379/2
    mongo: mongodb://localhost/nodeca-test

  email:
    transport: smtp://localhost:2525?ignoreTLS=true

  options:
    recaptcha: ~

  fork:
    www: 1
    qlight: 1
    qhard: 1
    nntp: 1

  search:
    api_endpoint: http://localhost:9314/
